//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SeraphimCore.rc
//
#define ID_MESH_VIEW                    0
#define IDI_ICON1                       106
#define IDI_MAIN                        106
#define IDI_BOXDEMO                     107
#define IDI_SMALL                       108
#define IDR_MENU1                       122
#define ID_RENDERSTATES_WIREFRAME       123
#define ID_FILE                         124
#define ID_RENDERSTATES_SOLID           125
#define ID_FILE_EXIT                    126
#define ID_DRAW_COLLISION               127
#define ID_COLLISION_ENTITY             128
#define ID_COLLISION_AABBTREE           129
#define ID_Menu                         130
#define ID_COLLISION_SPATIALNODE        131
#define ID_FILL_WIREFRAME               132
#define ID_FILL_SOLID                   133
#define ID_DRAW_STATS                   134
#define ID_STATS_FPS                    135
#define IDD_SceneViewDlg                136
#define ID_FILE_SAVE137                 137
#define ID_FILE_LOAD                    138
#define ID_FILE_NEW139                  139
#define ID_VIEW_CLASSBROWSER            140
#define IDI_ENTITY                      141
#define IDD_PROP_ED_DLG                 142
#define IDR_MENU2                       143
#define ID_EDITACTOR_ADDACTOR           144
#define IDD_MESH_DLG                    145
#define IDR_MENU3                       146
#define ID_FILE_IMPORT                  147
#define ID_IMPORT_XFILE                 148
#define ID_IMPORT_X                     148
#define ID_FILE_SAVE149                 149
#define IDR_MENU4                       152
#define ID_FILE_IMPORT153               153
#define ID_IMPORT_XFILE154              154
#define ID_FILE_SAVE155                 155
#define ID_FILE_LOAD158                 158
#define IDD_NEW_PACKAGE_DLG             159
#define ID_NEW_PACKAGE                  160
#define IDD_CHARACTER_DIALOG            162
#define IDR_MENU5                       163
#define ID_FILE_ADDANIMATION            164
#define ID_IMPORT_GSA165                165
#define IDD_ASSET_DIALOG                166
#define IDR_MENU6                       167
#define IDD_MATERIAL_IMPORT             168
#define IDB_BITMAP_MODEL_ROTATE         170
#define IDD_RESOURCE_LIST_DLG           171
#define IDC_CLASSTREE                   1001
#define IDC_MESH_TREE                   1001
#define IDC_CHARACTERS_TREE             1001
#define IDC_PROP_LIST                   1003
#define IDC_LIST                        1003
#define IDC_MESH_BG                     1007
#define IDC_MESH_LIST                   1008
#define IDC_PKG_EDIT                    1010
#define IDC_PACKAGES_COMBO              1013
#define IDC_CHARACTER_PACKAGE           1014
#define IDC_STATIC_CHARACTER            1015
#define IDC_CHOOSE_MESH_COMBO           1016
#define IDC_COMBO1                      1018
#define IDC_CHARACTER_PKG_COMBO         1018
#define IDC_ASSET_COMBO                 1018
#define IDC_MESHTECH_COMBO              1018
#define IDC_RESOURCELIST_COMBO1         1018
#define IDC_CHARACTER_COMBO             1019
#define IDC_SKELPROP_LIST               1021
#define IDC_TEX_LIST                    1026
#define IDC_SEQNAME_EDIT                1027
#define IDC_SEQSPEED_EDIT               1028
#define IDC_SEQUPDATE_BUTTON            1030
#define IDC_MAT_VIEW                    1031
#define IDC_SEQCOMBO                    1032
#define IDC_MATERIAL_COMBO              1033
#define IDC_SHADER_COMBO                1034
#define IDC_CHARADDSHADER               1034
#define IDC_TEX_EDIT                    1035
#define IDC_MESHTEX_COMBO               1037
#define IDC_EDITTEX_BUTTON              1038
#define IDC_ADDSHADER_BUTTON            1039
#define IDC_MESHSHADER_COMBO            1041
#define IDC_CHARFX_COMBO                1042
#define IDC_MATIMPORT_EDIT              1043
#define IDC_BUTTON1                     1044
#define IDC_UPCOLL_BUTTON               1044
#define IDC_SHADERTECH_BUTTON           1044
#define IDC_SHADERTECH_COMBO            1046
#define IDC_MESHTECH_BUTTON             1048
#define IDC_EDITSHADEPARAMS_BUTTON      1049
#define IDC_MESH_EDITPARM_BUTTON        1050
#define IDC_BUTTON_MODEL_ROTATE         1052
#define IDC_LIST1                       1052
#define IDC_RESOURCELIST_LIST1          1052
#define ID_IMPORT_ASE                   40001
#define ID_FILE_NEW40002                40002
#define ID_FILE_OPEN40003               40003
#define ID_FILE_IMPORT40004             40004
#define ID_IMPORT_GSA                   40005
#define ID_FILE_SAVE40006               40006
#define ID_VIEW_CHARACTERBROWSER        40007
#define ID_VIEW_BONES                   40008
#define ID_COLLISION_BONES              40009
#define ID_VIEW_MATERIALBROWSER         40013
#define ID_DRAW_EFFECTS                 40014
#define ID_EFFECTS_NORMALS              40015
#define ID_IMPORT_ASE_LEVEL             40018
#define ID_IMPORT_T3D                   40021
#define ID_FILE_IMPORT_IMG              40022
#define ID_FILE_SAVE_MAT_VIEW           40023
#define ID_FILE_OPEN_MAT_VIEW           40024
#define ID_FILE_NEW_MAT_PKG             40025
#define ID_NEW_MAP                      57600
#define ID_SAVE                         57603
#define ID_MESH_SAVE                    57603

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        172
#define _APS_NEXT_COMMAND_VALUE         40026
#define _APS_NEXT_CONTROL_VALUE         1053
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
